### ISSUE TITLE
1.9 - Battlearena deleting survival inventories / Not removing players from matches

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#67] opened 2016-03-13 18:40 UTC
Issues: (I had to turn off battlearena - it just got too bad)
1. Players are losing their survival inventories, because battlearena is not properly removing players from matches.  If they leave an arena successfully, put on their survival items, then log out, battlearena thinks they were in a match and removes their survival inventory.
2.  It is also an issue if a player does /arena leave, they sometimes dont get teleported out of the game, and cannot use commands, but their survival gear is on.  They are then stuck in the game forever.
   http://pastebin.com/KzH7if5Y
   http://pastebin.com/AwWdELc2
   http://pastebin.com/CBaAM7Fu
3. More Errors 
   http://pastebin.com/dJrUDmUk
   http://pastebin.com/su2hZdCd
   http://pastebin.com/xhU5vBdB
   http://pastebin.com/qrUu1LRH
   http://pastebin.com/gi6y99Ge
4. Dev version EUropia BattleArena_v3.9.10.10 attempt to fix above :

ERRRORS still happening and players are still stuck:
http://pastebin.com/dJrUDmUk
http://pastebin.com/su2hZdCd
http://pastebin.com/gi6y99Ge

*\* Caused by: java.lang.IllegalStateException: Unregistered scoreboard component**

**Comment by Europia79** [comment] 2016-03-20 19:04
Are there any errors ? If so, having them would make it easier to fix.

**Comment by tara81** [comment] 2016-03-20 19:33
http://pastebin.com/AwWdELc2
http://pastebin.com/Rv8wMdRp

**Comment by Europia79** [comment] 2016-04-18 09:21
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.14/

try BattleArena v3.9.10.14

Lemme know if it fixes the errors & the problem

**Comment by RednedEpic** [comment] 2019-03-12 21:16
I've fixed the survival inventory part as well as the serializing/deserializing part of inventories, however I can confirm that players are sometimes still not removed from the match after using /arena leave. (Won't let you join a game because "you are in an arena" but when you run /arena leave it says you are in one)

**Comment by RednedEpic** [comment] 2019-06-06 02:51
Please direct any comments intended for this Issue to #56. Inventory problem is solved, hence the other half of this issue is a duplicate.

**Comment by RednedEpic** [comment] 2019-06-25 18:19
Reopening this issue again. Inventory bug still persists and ran into it twice just a few minutes ago. Received many BattleTracker errors before this. It doesnt _appear_ they're linked at first glance, but the likelihood is quite high considering I haven't ran into this bug in months and the BattleTracker issue is as of today. Never had this issue before, and I closed this issue since I encountered a second inventory bug, which I did indeed patch.

https://pastebin.com/X8sLJ6Vt

Played a few matches with a friend, and found out only the winner lost their inventory. However, if I won a match and then played another and lost, my inventory was restored to what it was right before I started playing. Same story with my friend too. 

Also, when I run /arena j with items in my inventory, then run /arena l, I lose it all. Even after playing 10+ matches and losing one, I get the inventory back from what I had before I even joined the arena. 

Reloaded BattleTracker VIA /plugman reload and same problem.

Not receiving any errors in console like the ones shown above, and players don't appear to be stuck in matches. However, that issue is probably the most uncommon of them all and if anyone has anything regarding being stuck in matches, please redirect that to #56.

**Comment by RednedEpic** [comment] 2019-06-25 19:27
Identified the error.

https://pastebin.com/vZnMJdbs

**Closed** 2019-06-25 19:50 UTC
Labels: Confirmed, Confirmed Bug, Work in Progress

**Comment by RednedEpic** [comment] 2019-07-15 01:18
Accidentally referenced wrong issue in 8c13281aa6061480cb37a8b303787530821efb02, was meant to close #76.
