### ISSUE TITLE
Arena leave bug and experience bug

### ISSUE THREAD

**Issue by tehrenderr** [BattlePlugins/BattleArena#72] opened 2016-04-03 06:55 UTC
If I set it in the config.yml so disabledcommands is set to ['all'] it blocks all commands but when I set it to enabled commands [arena leave] it doesn't work even though it says it will override so players are unable to leave the arena. 

Another issue is players randomly getting exp from the arena when they leave or win. Here is the video
https://www.youtube.com/watch?v=zCQW8YPbw7k

**Comment by Europia79** [comment] 2016-04-04 20:08
What version is your server ?

**Comment by tehrenderr** [comment] 2016-04-04 20:38
The server is running paperspigot 1.7.10

**Comment by tehrenderr** [comment] 2016-04-05 21:25
Have you been able to look into it? I need this patched really soon please

**Comment by tehrenderr** [comment] 2016-04-06 21:48
Hello?

**Comment by Europia79** [comment] 2016-04-07 01:34
The problem with experience is that someone coded BattleArena specifically with 1.8 experience equations. I want to make the operation abstract to be able to handle any version of Minecraft (1.9, 1.8, 1.7, etc), but the experience equations of past commits aren't matching up with the internal NMS code. It's hard to decipher what's going on (no comments in the code). And hard to determine why they did things the way they did... So the differences make me wonder: "did they do it wrong ? Or just differently ?"

**Comment by tehrenderr** [comment] 2016-04-07 02:50
Is it possible to just make it so no experience is gained throughout any version after the battle is over? Also any word with the arena bug where I set it in the config.yml so disabledcommands is set to ['all'] it blocks all commands but when I set it to enabled commands [arena leave] it doesn't work even though it says it will override so players are unable to leave the arena.

**Comment by Europia79** [comment] 2016-04-08 02:05
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/util/CommandUtil.java#L10

That's the boolean logic that ultimately determines if a command gets cancelled.

The logic looks sound... Either the problem is with your config OR there's a comparison issue going on because you're allowing a sub-command (because it has two words instead of just one).

I need to see the exact contents of your config.

Also, i need you to run this command and show me your log file please:
```/arena enableDebugging commands true```

Or, for short-hand it's
```/arena ed commands true```

**Comment by tehrenderr** [comment] 2016-04-09 07:23
That command doesn't exist?

**Comment by tehrenderr** [comment] 2016-04-09 22:15
@Europia79 anything?

**Comment by Europia79** [comment] 2016-04-09 22:55
sorry, you're right...

```/battlearenadebug enableDebuggging commands true```

or for short:
```/bad ed commands true```

**Comment by tehrenderr** [comment] 2016-04-10 21:00
The debugging didn't show anything. Here are all my configs. We are using the latest battlearena and 1.7.10 spigot. In order for the XP glitch to work you need atleast 1 xp level. 
[BattleArena.zip](https://github.com/BattlePlugins/BattleArena/files/211996/BattleArena.zip)

**Comment by Europia79** [comment] 2016-04-11 00:50
I need your server log files.

```bad ed commands true``` executes this method:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/executors/BattleArenaDebugExecutor.java#L59

toggles this boolean:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/executors/BattleArenaDebugExecutor.java#L74

And sends one of two possible messages for success or failure of the commands:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/executors/BattleArenaDebugExecutor.java#L83

Which command message did you get ?

Then later, when a player tries to run a command, one of two possible events is triggered:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/objects/joining/ArenaMatchQueue.java#L795-L796
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/competition/match/ArenaMatch.java#L346-L347

depending on if they're in queue or if they're inside a match.

Either way, ```CommandUtil.shouldCancel()``` is called:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/util/CommandUtil.java#L10

i'll take a look at the logic again.

**Comment by tehrenderr** [comment] 2016-04-11 00:55
[latest.zip](https://github.com/BattlePlugins/BattleArena/files/212108/latest.zip)

**Comment by Europia79** [comment] 2016-04-11 02:29
change your **BattleArena/config.yml** to
```
enabledCommands: [arena, list]
```

This should temporarily fix the "/arena leave" issue... Hopefully for the next release, i can fix both of these issues.

**Comment by tehrenderr** [comment] 2016-04-11 03:38
Thanks. Let me know if you can do anything about the experience issue.

**Comment by Europia79** [comment] 2016-04-11 05:13
This build should fix the issue with "arena leave" and all other sub-commands:
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.12/

**Comment by tehrenderr** [comment] 2016-04-11 05:22
Awesome, is there anything you need me to do to help test the experience bug?

**Comment by Europia79** [comment] 2016-04-11 05:26
http://minecraft.gamepedia.com/Experience

Help testing would be awesome. i'll let ya know

**Comment by Europia79** [comment] 2016-04-11 05:42
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.13/

This one is better. It shouldn't really affect you because you use 'all' for disabledCommands... but this update fixes ```disabledCommands``` to restrict sub-commands. The one you have should allow you to put sub-commands for ```allowedCommands```

**Comment by tehrenderr** [comment] 2016-06-17 19:20
I'm using 1.8 now with this jar you sent me and leaving doesn't seem to work again?
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.13/

here is the debug message:
event Messafe=/arena leave  isCancelled=false

Iv'e tried putting my config as [arena, list] and [arena leave, list]

**Comment by RednedEpic** [comment] 2019-06-25 20:07
> The problem with experience is that someone coded BattleArena specifically with 1.8 experience equations. I want to make the operation abstract to be able to handle any version of Minecraft (1.9, 1.8, 1.7, etc), but the experience equations of past commits aren't matching up with the internal NMS code. It's hard to decipher what's going on (no comments in the code). And hard to determine why they did things the way they did... So the differences make me wonder: "did they do it wrong ? Or just differently ?"

I implemented this in BattleBukkitLib about a month or so ago. Experience calculations are now version-dependent and the sub command bug appears to be fixed. Closing issue for now.

As usual, if this issue comes back up in the future, please comment here or reach out to us on [Discord](https://discord.gg/tMVPVJf) and I'll reopen it.

**Closed by RednedEpic** 2019-06-25 20:07 UTC
Labels: Work in Progress
