### ISSUE TITLE
Battlearena2 problems - Stuck in match after leaving, no queue end if not enough players

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#13] opened 2015-02-27 02:40 UTC
Problems :
 1. Players sometimes cannot enter battlearena, it says they are in a match when they are not.
2. If players are in queue in the waitroom and there are not enough players after the timestart, they stay in the waitroom forever and don't get removed from that queue. However, when new players join the same game, they are in a different queue. So this player gets left out forever.(or until /bg leave and /bg join again)

**Comment by xion87** [comment] 2015-03-17 09:35
i an confirm this, happen somwthing, when more player join same game/different games

**Comment by tara81** [comment] 2015-04-16 07:33
The only fix for this is to turn off the minigame /arena cancel  =/

**Comment by Zach443** [comment] 2015-04-18 17:04
@tara81 @xion87 I have experienced this as well, and I am investigating the cause. Once I figure it out I will add it to the feature list for 4.0, located at issue #14

**Comment by clovisd** [comment] 2015-04-26 21:27
I haven't experienced this on my server using the latest BA. Albiet, I didn't do much testing but it never occurred to me or fellow players. This could be related to how the server handles players and worlds with regards to another plugin.

**Comment by clovisd** [comment] 2015-04-26 22:45
Also, this appears to be two different reports in one. Can you please separate the reports?

This makes it infinitely easier for us to keep track of the bugs when fixing them and planning ahead.

Thank you.

**Comment by lDucks** [comment] 2015-07-05 21:54
Marked invalid. Closing.

**Closed by lDucks** 2015-07-05 21:54 UTC
Labels: Invalid

**Comment by Europia79** [comment] 2015-07-06 05:37
This does give me an idea for different style of queue... more like World of Warcraft... I haven't played in a long time... but if i remember correctly, you can join queues... but continue playing like normal... And the queue will notify you that enough players have joined...

This is instead of how it currently is... Where when you join a queue, you get teleported to a waiting room, where you have a wait until enough players join, for the match to start.

**Comment by Zach443** [comment] 2015-07-06 06:21
@Europia79 If you do not set a waitron you will continue playing like normal (and not be teleported), as you are explaining.

**Comment by Europia79** [comment] 2015-07-06 07:12
@Zach443 but don't you also need the waitroom to select your ArenaClass ?

**Comment by xion87** [comment] 2015-07-06 10:46
Europia like a message that popup with Join or Reject (in clickable json format?)

**Comment by Zach443** [comment] 2015-07-06 14:03
@Europia79 Players can choose their class with the "/arena class <className>" command I believe. Also, I have seen people put class signs in team spawns of their arenas before.

**Comment by Europia79** [comment] 2015-07-06 20:05
> like a message that popup with Join or Reject (in clickable json format?)

That's a good idea. Just need to make sure there's enough Prestart time to choose your ArenaClass

**Comment by xion87** [comment] 2015-07-07 17:14
well maybe add a option that open a gui with classes, and select it, so no need hub, and add a ready check :)

**Comment by tara81** [comment] 2015-09-26 23:23
I still have this issue on my server. :( I am using the latest version.

**Comment by xion87** [comment] 2015-09-27 07:51
same here stil not fixed, the best way is restart the server each day...

**Comment by tara81** [comment] 2015-10-07 06:26
Yeah i do the same or run the command /arena cancel all once a day .
