### ISSUE TITLE
Players becoming invisible

### ISSUE THREAD

**Issue by CassandraWipf** [BattlePlugins/BattleArena#48] opened 2015-08-09 18:00 UTC
Platform: Spigot 1.8.7
Battle Arena Version: v3.9.10.4
World Guard Version: 6.0.0-snapshot.1582
World Edit Version:
Permission Plugin: zpermissions
Other Plugins: 
Description: Occasionally when a player joins a tourney they will become invisible, and they will have to re-log to fix it, /v does not fix it, and invisible potions are disabled so it would not be a player drinking one and going into a tourney.
Info needed for Replication:

**Comment by Europia79** [comment] 2015-08-12 23:56
@CassandraWipf 

go into ```plugins/BattleArena/config.yml``` and look for an option ```enableInvisibleTeleportFix:```. Set this to **true** and lemme know if it fixes your invis bug.

**Comment by voigtman** [comment] 2015-08-27 07:34
I have this issue and this is set to true in the config.

**Comment by Europia79** [comment] 2015-08-27 21:44
sorry I misspoke what you're supposed to do is toggle to setting

**Comment by voigtman** [comment] 2015-08-28 07:37
Toggle to setting? what do you mean?

**Comment by jjkrause** [comment] 2015-09-24 14:14
Toggle means if its true, set it to false and if it's false,set it to true.

**Comment by voigtman** [comment] 2015-09-24 16:49
Ok my players do disappear, and my setting has been toggled to both true and false and they continue to disappear.


--
Jason Houge
http://jasonhougecom

**Comment by xion87** [comment] 2015-12-18 10:21
got a similiar issue here...

**Comment by Blackyvk** [comment] 2016-06-07 16:52
this bug still persists and its very annoying, there is always 1 player on disadvantage.

**Comment by Blackyvk** [comment] 2016-06-11 23:05
Ok, I found this bug happens more often when you teleport to an arena from a different world.

**Comment by RednedEpic** [comment] 2019-03-12 22:57
Have never experienced this bug before for the years that I've been using BattleArena. If you're still using the plugin and still have this problem (or anyone else for that matter), please comment on this issue stating it still happens to you or message us here https://discord.gg/tMVPVJf on Discord. 

This is _most likely_ due to a plugin interfering with BattleArena.

**Comment by IgnisAlienus** [comment] 2019-04-07 23:08
I'm currently having issues with this.  I have it set up so that the arena is in a different world.  It's hard to pinpoint exactly who goes invisible to other players.  It does happen as the player clicks the join or leave sign or when the game ends and the players are teleported out.

**Comment by RednedEpic** [comment] 2019-04-07 23:10
> I'm currently having issues with this. I have it set up so that the arena is in a different world. It's hard to pinpoint exactly who goes invisible to other players. It does happen as the player clicks the join or leave sign or when the game ends and the players are teleported out.

And to confirm, you've tried with both true and false options for enableInvisibleTeleportFix and still had this problem?

**Comment by IgnisAlienus** [comment] 2019-04-07 23:10
> > I'm currently having issues with this. I have it set up so that the arena is in a different world. It's hard to pinpoint exactly who goes invisible to other players. It does happen as the player clicks the join or leave sign or when the game ends and the players are teleported out.
> 
> And to confirm, you've tried with both true and false options for enableInvisibleTeleportFix and still had this problem?

Yes

**Comment by RednedEpic** [comment] 2019-04-07 23:12
What other plugins do you currently have installed? Have you tried replicating this bug with only BattleArena installed? It could very well be another plugin interfering with BA.

**Comment by IgnisAlienus** [comment] 2019-04-07 23:32
ArenaBattleRoyale
BattleArena
BattleTracker
CleanroomGenerator
EssentialsX
EssentialsXAntiBuild
EssentialsXProtect
EssentialsXSpawn
LuckPerms
Multiverse-Core
Multiverse-Inventories
Multiverse-Portals
Multiverse-SignPortals
PerWorldServerChat
PluginConstructorAPI
QualityArmory
Spigot-CommandSigns
Vault
WorldEdit
WorldGuard

I also just tried putting the join sign in the same world as the arena and arena's lobby.  Still had invisible player issue.  I'll start going through and disabling a plugin to see if I can find out which one might be causing problems.

**Comment by IgnisAlienus** [comment] 2019-04-07 23:56
> Multiverse-Core
> Multiverse-Inventories
> Multiverse-SignPortals
> 
> I also just tried putting the join sign in the same world as the arena and arena's lobby. Still had invisible player issue. I'll start going through and disabling a plugin to see if I can find out which one might be causing problems.

It's definitely linked to multiverse.  I disabled multiverse and set the default level to the map the arena was in.  I then created a join sign there and joined up with 2 accounts and no invisibility issue when joining/leaving the arena

**Comment by RednedEpic** [comment] 2019-04-07 23:58
> It's definitely linked to multiverse. I disabled multiverse and set the default level to the map the arena was in. I then created a join sign there and joined up with 2 accounts and no invisibility issue when joining/leaving the arena

Alright, that's good to know. What version of Spigot and Multiverse are you running?

**Comment by IgnisAlienus** [comment] 2019-04-08 00:02
Multiverse-core 2.5.0
Multiverse-inventories 2.5.0-snapshot
multiverse-signportals-2.4
When I run /version I get "This server is running CraftBukkit version git-Spigot-5629554-4c8327f (MC:1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) You are 4 version(s) behind.

**Comment by IgnisAlienus** [comment] 2019-04-08 00:37
I found these version below on bukkit's website which were more recent than spigot's versions.  
Multiverse-core-3.0.0-snapshot
same inventories version
Multiverse-signportals-3.0.0-snapshot
These versions are listed for Minecraft 1.13
I updated to them and still have invisibility issue.

**Comment by xion87** [comment] 2019-04-08 18:54
lol a reply after 4 years of innativity

**Comment by xion87** [comment] 2019-04-09 08:15
offtopic: so battlearena is still alive?

**Comment by IgnisAlienus** [comment] 2019-04-10 03:04
> Yep, it’s back and active again 😀

I've been looking around to try to solve on my end.  I tried using a different multiple world plugin with no luck.  I looked around and saw some other discussions of other people have the same issue with any plugin that teleports to an arena and back.  I also saw some discussion about code they put in their plugins to refresh the players or something.  I'm not a programmer so I have no idea what they would have put into their codes.

**Comment by RednedEpic** [comment] 2019-04-12 02:49
> > Yep, it’s back and active again 😀
> 
> I've been looking around to try to solve on my end. I tried using a different multiple world plugin with no luck. I looked around and saw some other discussions of other people have the same issue with any plugin that teleports to an arena and back. I also saw some discussion about code they put in their plugins to refresh the players or something. I'm not a programmer so I have no idea what they would have put into their codes.

So to confirm, even using other multi-world plugins causes the same problem? Have you tried possibly making an arena in the nether world and trying to teleport to the arena there from the overworld? The reason I ask this is because the nether world (and end world as well) are generated through Bukkit itself and it'd be interesting to know if the problem still persists among these worlds as well.

**Comment by IgnisAlienus** [comment] 2019-04-12 03:04
I can try that out sometime tomorrow and will let you know. I'm out of town at them moment.

**Comment by voigtman** [comment] 2019-04-12 04:28
In my experience, when I made the initial post, my battle arenas were all on the same world as the players - so they weren’t always teleporting from one world to another. Example - I had this installed on my SkyBlock and they might duel and teleport to a set dueling island and one player might be invisible. 

Founder and co-owner
VoigtlandMC
play.voigtlandmc.net

**Comment by IgnisAlienus** [comment] 2019-04-12 22:12
> I can try that out sometime tomorrow and will let you know. I'm out of town at them moment.

So I set the arena in the default world's nether and set a join sign in the overworld and still had the invisible player issue.  This is effects other arena plugins I've tried and doing a google search on it I can find threads going back 8 years about people having this issue and relating it to a bukkit or even vanilla bug.  I've seen some saying the there is lines of code that can be added to plugins to counteract the invisible player.  There's gotta be a way to make a plugin that would fix it for all plugins.

**Comment by RednedEpic** [comment] 2019-04-13 02:12
Spoke to @IgnisAlienus on Discord and we resolved the problem. It lied within the PerWorldServer plugin. I'll be reaching out to the developer and letting him know of the problem, but it doesn't appear like he's quite as active on Spigot anymore. I do however have his Discord and will be messaging him there.

But as the to the original problem here, I cannot find any threads or anyone else having a similar issue since 2015. However in those threads, I didn't see anyone link them up to the Bukkit/Mojang issue that the `enableInvisibleTeleportFix` was intended to fix back in 2012.

For the time being, I will be closing this issue and if anyone has a similar problem, I ask that you open up a new issue and list the steps to recreate the problem and list all the plugins you have installed.

**Closed by RednedEpic** 2019-04-13 02:12 UTC
Labels: More Info Needed, Unconfirmed Bug
